moot.language = {

  // the language code
  $code: 'es',

  /* New stuff */
  address_now: 'Escribe tu dirección: ',
  open_pw: 'Por favor, pulsa el botón de abajo para abrir un cuadro de diálogo para cambio de contraseña',
  non_anon: 'Tienes que haber Iniciado Sesión para realizar esta acción',

  plan: 'Plan',
  trial: 'Empieza una prueba gratuita',

  is_private: "Esta comunidad es privada",
  owner_msg: "Tu mensaje para el dueño del foro... (Opcional)",
  req_access: "Solicitud de acceso",
  req_sent: "Solicitud de acceso enviada",
  or_join: "o <a>Únete</a> para acceder a la comunidad.",
  save_with: "Ahorra un 20% con facturación anual",
  rem_post: "¿Eliminar este mensaje?",
  is_spam: "¿Este mensaje es spam?",

  channels: 'Canales',
  ch_name: 'Nombre del Canal',
  ban:  'Expulsar usuario',
  banned:  'Expulsado',
  days:  'Días',
  forever: 'Siempre',
  slogan:  'Foros y Comentarios gratis de Muut',

  add: '+ Añadir',
  addons: 'Complementos',
  myaccount: "Mi cuenta",
  untitled: "Sin título",
  design: "Diseño",

  no_title: "El título no debe estar vacío",
  designer: "Diseñador",
  developer: "Desarrollador",

  ban_acc: 'Cuenta bloqueada',
  ban_msg: 'Estás temporalmente expulsado de este foro por violar sus políticas. Tiempo restante:',
  banned4: 'Ya no puedes publicar en este foro.',
  warning: 'Atención',
  profanity: 'No están permitidos los insultos en este foro. El abuso continuado de ésta política provocará su expulsión.',

  img_needed: "Por favor sube una imagen",
  max: 'El tamaño máximo de imagen es 4MB',
  yes: 'Sí',
  upload: 'Subir imágenes',
  show: 'Mostrar',
  hide: 'Ocultar',
  invisible: 'Invisible',
  givebody: 'El cuerpo no puede estar vacio.',
  show_old: 'Mostrar respuestas más antiguas',
  show_more: 'Mostrar más respuestas',
  show_new: 'Mostrar respuestas más recientes',
  start: 'Comienza un nuevo tema...',
  single: 'Palabra sola',
  bold: 'Negrita',
  italics: 'Cursiva',
  monospaced: 'Monoespaciada',
  learn: 'Saber más...',
  settings: 'Ajustes',
  error: 'Oops, un error. Por favor cópialo en el portapapeles, y recarga. ¡Lo corregiremos!',
  body: 'Texto del cuerpo',
  admin: 'Admin',
  someone: 'Alguien',
  writing: 'Escribiendo...',
  manage: 'Gestionar',
  admin: 'Administrar',
  fullview: 'Vista completa',
  title: 'Título',
  link: 'Enlace',
  avatar: 'Cambiar avatar',
  upgrade_link: 'Actualización',
  branding: 'Creación de Marca (Branding)',
  logo: 'Logotipo',
  css: 'Archivo CSS',

  /* End new stuff */
  username_fail: 'Usar letras, números o guiones',
  all: 'Todo', // or alternatively: All
  anon_1: 'anónimo',
  anon: 'anónimos',
  badforum: 'Foro no válido',
  c_acc1: 'Tu cuenta está ahora habilitada en todos los sitios que usen Muut',
  c_acc: 'Cuenta confirmada',
  c_email: 'Email confirmado',
  cancel: 'Cancelar',
  change: 'Cambiar',

  changepw: 'Cambiar contraseña',
  close: 'Cerrar',
  collapse: 'Plegar
  todo',
  comm_count_1: 'comentario',
  comm_count_n: 'comentarios',
  comment1: 'Sé el primero en comentar...',
  comment: 'Comentar...',
  edit: 'Editar',
  email: 'Email',
  email_taken: 'Este email ya está registrado',
  emailtip: 'Tu email nunca será compartido',
  enter: 'ctrl + enter',
  expired1: 'Hemos enviado uno nuevo. Por favor revisa tu email.',
  expired: 'Este enlace ha expirado',

  feed: 'Míos',

  help2: 'Enviar',
  help3: 'Citado',
  help5: 'Código, lenguaje adivinado',
  help6: 'Código html',
  in_forum: 'en',
  invalid: 'Valor no válido',
  join: 'Unirse a Muut',
  later: 'Más tarde...',
  less: 'Menos',
  like: 'Me gusta',
  likepost: 'Me gusta ésta entrada',
  loading: 'Cargando...',
  login: 'Iniciar sesión',
  login1: 'Primero inicia sesión',
  login_and: "Iniciar sesión y",

  logout: 'Salir',
  mark: 'Ofensivo o spam',
  mean: 'Te refieres a',
  name: 'Mostrar nombre',
  nametip: 'Tu nombre real, por el que la gente te reconocerá',
  newpass: 'Nueva contraseña',
  noresults: 'Sin resultados para',
  nospam: '¡Sin spam en tu foro!',
  notexist: 'No existe.',
  notify: 'Notificarme novedades sobre Muut',
  ok: 'OK',
  online: 'Online',
  post: 'Enviar',
  preview: 'Previo',
  progress: ['Cargando...', 'Todavía trabajando...', 'y trabajando...', 'Abandonando'],
  reconnect: 'Reconectando...',
  removepost: 'Eliminar esta entrada',
  reply: 'Contestar...',
  replybtn: 'Contestar',
  save: 'Guardar cambios',
  saved: 'Guardados',
  search: 'Buscar',
  select: 'Seleccionar foro',
  setup: 'Configurar ahora',
  showing: 'Mostrando',
  spam: 'Spam',
  step1: 'Hemos enviado un email de confirmación. ¡Tu email no será actualizado antes de que completes este paso!',
  step: 'Un paso más',
  terms: 'Acepto los <a>términos del servicio</a>.',
  thanks: '¡Gracias!',
  uname_len: 'Escribe 4 caracteres o más',
  uname_taken: '¡Este nombre de usuario está ocupado!',
  unametip: 'Esto no puede ser cambiado después',
  undo: 'Deshacer',
  unlike: 'No me gusta',
  unspam: 'No spam',
  unver1: 'Cuenta no verificada',
  unver2: 'Por favor revisa tu email para verificar tu cuenta.',
  unver3: 'Enviar un nuevo código de verificación',
  unver4: "Enviado. Por favor, revisa tu bandeja de entrada.",
  unver: 'No verificado',
  unwall: 'Dejar de vigilar',
  unwatch: 'No vigilar',
  upgrade2: 'Muut usa WebSockets o CORS para la comunicación entre dominios. Funciona en todos los navegadores modernos excepto en Opera 11 y IE7.',
  upgrade: 'Por favor, actualice su navegador',
  username_taken: 'Este nombre de usuario está ocupado',
  watch: 'Vigilar nuevas respuestas',
  welcome1: 'Por favor revisa tu email para completar la registración. Si no recibes un email en un minuto o dos, revisa tu carpeta de Correo no deseado.',
  welcome2: 'Por favor, proporciona un nombre de usuario',
  welcome: 'Bienvenido a Muut',
  you: 'Tú',

  // times
  months: "Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Set,Oct,Nov,Dic",
  min:  'm',
  hour: 'h',
  day:  'd',
  week: 's'

}
